### ISSUE TITLE
VariantEncumbrance stopped applying speed penalties 

### ISSUE THREAD

**Issue by apoapostolov** [VanirDev/VariantEncumbrance#31] opened 2021-02-13 22:26 UTC
Although my players are encumbered, the mod no longer seems to apply any modifiers to speed since 5E 1.2.0

![image](https://user-images.githubusercontent.com/4083812/107863236-25c9e600-6e5b-11eb-8a95-8731b4bf33c4.png)

**Comment by Gorvaine** [comment] 2021-03-30 13:51
Same

**Comment by Daxiongmao87** [comment] 2021-08-25 05:59
This still seems to be an issue with the latest version.  No matter the weight, speed stays the same.

**Comment by p4535992** [comment] 2021-08-25 07:21
Please guys you have to try to give me more information on a technical level ... Check if there is any exception on the web console.

Now the speed penalties are activated with the active effects. Don't you see any effect on the "effects" tab?

Below I have put an example of a issue template (tomorrow I will prepare the one for github). 

**Environment Details**

Foundry VTT Version: e.g. 0.8.9
Operating System: e.g. [Linux]
How Are You Using Foundry: e.g.  [Linux,Native Application (Electron), Chrome]
Which Game System: e.g. Dungeons and Dragons 5th Edition, version 1.4.1
Modules Enabled?: e.g Yes or no
Module version: VERSION OF THE MODULE "VariantEncumbrance"
OS, Hosting, Browser (if applicable): e.g. Linux/Node/Chrome

**Description of the issue:**

Exception on the web console , screenshot , step to step for reproduce this issue, ecc.

**Comment by p4535992** [comment] 2021-09-04 12:28
Thi should be fixed with 0.5.12

**Closed as completed by p4535992** 2021-09-04 12:28 UTC
